apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  selector:
    matchLabels:
      run: python
  replicas: 1
  template:
    metadata:
      labels:
        run: python
    spec:
      containers:
      - name: python
        image: gcr.io/tribally-host-prj-s1/myapp:latest
        ports:
        - containerPort: 8080       
---
apiVersion: v1
kind: Service
metadata:
  name: python
  labels:
    run: python
spec:
  ports:
  - port: 80
  targetPort: 8080
  selector:
    run: python
